### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lancerossdev** [lancerossdev/deployrocket#1]
- [x] Add light mode (it matters lol)
- [x] Add your own team images on about section
- [x] Create a placeholder login and about the products
- [x] Add new pages about the products
- [x] Add 404 Page
